### ISSUE TITLE
Mixins refmap is only applied to "jar" task

### ISSUE THREAD

**Issue by andriihorpenko** [neoforged/ModDevGradle#208]
## Description
Any custom tasks with Jar type do not receive mixins refmap. Therefore, tasks like "shadowJar" won't get one.

## Cause
This is likely due to how MDG adds refmaps to Jar tasks. MDG filters out tasks named `sourceSet.getJarTaskName()`, leaving other tasks untouched.
https://github.com/neoforged/ModDevGradle/blob/77ffcc8464ceaabcce087aff510d27104eafe0e1/src/legacy/java/net/neoforged/moddevgradle/legacyforge/dsl/MixinExtension.java#L50

## MDG vs NeoGradle
I'm using NG in my other project with custom Jar tasks. Interestingly, NG _does_ add refmaps to all my custom Jar tasks without any additional configuration.

## Demo repository
https://github.com/andriihorpenko/mdg-demo

1. Select "issue1-demo" branch
2. Run "build" task
3. Inspect `build/libs/examplemod-1.0.0.jar` and `build/libs/examplemod-1.0.0-custom.jar`.
The `custom` one won't have a refmap file, while original one will.

**Comment by Matyrobbrt** [comment]
This is expected behaviour. It is not trivial to determine what source sets each jar is sourced from (certainly with some custom tasks you simply can't) and therefore we're only adding the refmap to the "safe" jar, the one linked to the sourceset via the name. For any custom tasks you're expected to add the refmap manually (that is why `mixin.add` returns a provider with the refmap file)
